message_board/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='test_app/index.html'), name='index'),
    path('accounts/', include('allauth.urls')),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', LoginView.as_view(), name='login'),
    path('test_app/', include('test_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

test_app/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
    path('', ArticleList.as_view(), name='index'),
    path('article/create/', ArticleCreate.as_view(), name='article_create'),
    path('<int:pk>/article/update', ArticleUpdate.as_view(), name='article_update'),
    path('<int:pk>/delete/', ArticleDelete.as_view(), name='delete'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('confirm', ConfirmUser.as_view(), name='confirm_user'),
    path('login/', LoginView.as_view(), name='login'),
    path('signup', SignupView.as_view(), name='signup'),
    path('<int:pk>/comment/create', CommentCreate.as_view(), name='comment_create'),
    path('article/detail/<int:pk>/', ArticleDetail.as_view(), name='article_detail'),
    path('article/read/<int:pk>/', ArticleView.as_view(), name='article_read'),
    path('<int:pk>/edit', CommentUpdate.as_view(), name='comment_edit'),
    path('comment/delete/<int:pk>/', CommentDelete.as_view(), name='comment_delete'),
    path('<int:pk>/response/', Response.as_view(), name='response'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

test_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import BaseUserManager
from django.urls import reverse


class CustomUserManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError('Email должен быть установлен')
        email = self.normalize_email(email)
        user = self.model(email=email, username=username)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password=None):
        user = self.create_user(email, username, password)
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractUser):
    code = models.CharField(max_length=8, blank=True, null=True)
    email = models.EmailField(verbose_name='Email', max_length=60, unique=False)
    username = models.CharField(verbose_name='Имя пользователя', max_length=30, unique=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    objects = CustomUserManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin


class Article(models.Model):
    objects = None
    TYPE = (
        ('tank', 'Танки'),
        ('heal', 'Хилы'),
        ('dd', 'дд'),
        ('buyers', 'Торговцы'),
        ('gildmasters', 'Хозяева_гильдий'),
        ('quest', 'квест'),
        ('smith', 'Кузнецы'),
        ('tanner', 'Кожевники'),
        ('potion', 'Зельевики'),
        ('spellmasters', 'Хозяева_заклятий'),
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=88)
    text = models.TextField()
    category = models.CharField(max_length=16, choices=TYPE, default='Танки')
    media = models.FileField(upload_to='media/', default='default.png')

    def preview(self):
        preview = f'{self.text[0:123]} + "..."'
        return preview

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article_detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        if not self.author:
            self.author = self.author if self.author else self.request.user
        super().save(*args, **kwargs)


class Comment(models.Model):
    objects = True
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='автор комментария')
    commentArticle = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name='комментарий к статье :')
    text = models.TextField(verbose_name='коммент')
    created_at = models.DateTimeField(auto_now_add=True,verbose_name='время создания')
    status = models.BooleanField(default=False, verbose_name='статус')

    def __str__(self):
        return f'{self.commentUser} : {self.text} [:20] + ...'

    def get_absolute_url(self):
        return reverse('article_read',kwargs={'pk': self.commentArticle_id})

    class Meta:
        verbose_name = 'комментарий'
        verbose_name_plural = 'комментарий'
        ordering = ['id']

test_app/forms.py
from allauth.account.forms import SignupForm

from django.conf import settings
from django.core.mail import send_mail
from django.forms import ModelForm, TextInput, Textarea, ClearableFileInput, Select
from django import forms
from string import hexdigits

import random

from .models import Article, Comment


class CommonSignupForm(SignupForm):
    def save(self, request):
        user = super(CommonSignupForm, self).save(request)
        user.is_active = False
        code = ''.join(random.sample(hexdigits, 5))
        user.code = code
        user.save()
        send_mail(
            subject=f'Код для активации',
            message=f'Код активации вашего аккаунта: {code}',
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[user.email],
        )
        return user


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'text', 'category', 'media']
        widgets = {
            'title': TextInput(attrs={'class': 'form-control', 'placeholder': 'Название объявления'}),
            'text': Textarea(attrs={'class': 'form-control', 'placeholder': 'Текст объявления'}),
            'media': ClearableFileInput(attrs={'class': 'form-control', 'placeholder': 'изображение'}),
            'category': Select(attrs={'class': 'form-control', 'placeholder': 'категория'})
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text': 'Введите текст'}
        widgets = {'text': forms.Textarea(attrs={'class': 'form-text', 'cols': 100, 'rows': 10})}


class ArticleDeleteForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'text', 'category', 'media']


class CommentDeleteForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']


class ResponseForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

test_app/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.core.mail import EmailMessage, send_mail
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, TemplateView, ListView, DetailView, DeleteView, View, \
    RedirectView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import logout
from django.http import request, HttpResponseRedirect
from django.http import Http404

from message_board import settings
from .forms import ArticleForm, CommonSignupForm, CommentForm, CommentDeleteForm, ResponseForm

from .models import Article, Comment, User


@permission_required('polls.add_choice')
@login_required
def my_view(request):
    # Your view logic here
    return render(request, 'default.html')


def logout_view(request):
    logout(request)
    return redirect('index')


class ConfirmUser(UpdateView):
    model = User
    context_object_name = 'confirm_user'
    fields = ['code']

    def post(self, request, *args, **kwargs):
        if 'code' in request.POST:
            user = User.objects.filter(code=request.POST['code'])
            if user.exists():
                user.update(is_active=True)
                user.update(code=None)
            else:
                return render(self.request, 'registration/invalid_code.html')
        return redirect('account_login')


class SignupView(CreateView):
    form = CommonSignupForm
    model = User
    template_name = 'registration/signup.html'
    fields = ['username', 'email']

    def get_success_url(self):
        return reverse('confirm_user', kwargs={'pk': self.object.pk})


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'test_app/profile.html'
    pk_url_kwarg = 'pk'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        articles = Article.objects.filter(author=self.request.user)
        context['articles'] = articles
        return context


class ArticleList(ListView):
    model = Article
    template_name = 'test_app/index.html'
    context_object_name = 'article'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        articles = Article.objects.filter()
        context['articles'] = articles
        return context


class ArticleView(View):
    model = Article
    form_class = ArticleForm
    template_name = 'test_app/article_read.html'
    context_object_name = 'article'
    pk_url_kwarg = 'pk'

    def get(self, request, pk):
        try:
            article = self.model.objects.get(pk=pk)
        except self.model.DoesNotExist:
            raise Http404("Статья не найдена")

        context = {
            self.context_object_name: article,
        }
        return render(request, self.template_name, context)


class ArticleCreate(LoginRequiredMixin, CreateView):
    permission_required = ('test_app.article_create',)
    raise_exception = True
    model = Article
    form_class = ArticleForm
    template_name = 'test_app/article_create.html'
    pk_url_kwarg = 'pk'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def form_save(self, form):
        article = form.save(commit=False)
        article.author = self.request.user
        form.save()
        return redirect('profile', self.object.pk)


class ArticleDetail(LoginRequiredMixin, DetailView):
    permission_required = ('test_app.article_create',)
    model = Article
    template_name = 'test_app/article_detail.html'
    context_object_name = 'article'
    pk_url_kwarg = 'pk'

    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Article, pk=pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['article_id'] = self.kwargs.get('pk')
        return context


class ArticleUpdate(LoginRequiredMixin, UpdateView):
    permission_required = ('test_app.article_update',)
    model = Article
    form_class = ArticleForm
    template_name = 'test_app/article_update.html'
    pk_url_kwarg = 'pk'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def form_save(self, form):
        article = form.save(commit=False)
        article.author = self.request.user
        form.save()
        return redirect('article_detail', self.object.pk)


class CommentCreate(LoginRequiredMixin, CreateView):
    model = Comment
    template_name = 'test_app/comment_create.html'
    form_class = CommentForm
    pk_url_kwarg = 'pk'

    def form_valid(self, form):
        form.instance.commentUser = self.request.user
        form.instance.commentArticle = Article.objects.get(pk=self.kwargs['pk'])
        return super().form_valid(form)

    def form_save(self, form):
        comment = form.save(commit=False)
        comment.author = self.request.user
        form.save()
        comment_user_email = form.instance.commentArticle.author.email
        send_email(to_email=comment_user_email, subject='Ваш коммент прочитали', message='Ваш коммент прочитали.')
        return redirect('article_read', self.object.pk)


def send_email(to_email, subject, message):
    email = EmailMessage(subject, message, to=[to_email])
    email.send()


class CommentUpdate(LoginRequiredMixin, UpdateView):
    permission_required = ('test_app.comment_edit',)
    model = Comment
    form_class = CommentForm
    template_name = 'test_app/comment_edit.html'
    pk_url_kwarg = 'pk'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Comment, pk=pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_id'] = self.kwargs.get('pk')
        return context


class ArticleDelete(LoginRequiredMixin, DeleteView):
    model = Article
    template_name = 'test_app/delete.html'
    success_url = reverse_lazy('profile')


class CommentDelete(LoginRequiredMixin, DeleteView):
    model = Comment
    form_class = CommentDeleteForm
    template_name = 'test_app/comment_delete.html'
    success_url = reverse_lazy('index')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return HttpResponseRedirect(self.get_success_url())


class Response(LoginRequiredMixin, RedirectView):
    success_url = reverse_lazy('index')

    def get_redirect_url(self, *args, **kwargs):
        pk = kwargs.get('pk', None)
        self.send_mail(pk)

        return self.success_url

    def send_mail(self, pk):
        comment = get_object_or_404(
            Comment,
            pk=pk
        )

        comment.status = True
        comment.save()

        # Отправка уведомления
        subject = 'Комментарий прочитан'
        message = f'Пользователь {self.request.user.username} прочитал ваш комментарий'
        recipient_list = [comment.commentUser.email]
        send_mail(subject, message, settings.EMAIL_HOST_USER, recipient_list)

test_app/templates/test_app/account_inactive.html
{% extends "flatpages/default.html" %}

{% load i18n %}

{% block head_title %}Активация{% endblock %}

{% block content %}
    <h1 style="...">Активация</h1>
    <form action="{% url 'confirm_user' %}" method="post" style="...">
        {% csrf_token %}
        <label>
            <input class="text" type="text" name="code" placeholder="Введите код активации">
        </label>
        <input type="submit" value="Подтвердить">
    </form>
{% endblock %}

test_app/templates/test_app/article_create.html
{% extends 'flatpages/default.html' %}
{% block content %}
    <div class="features">
        <h1>Создание нового объявления</h1>

        <form action="{% url 'article_create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.category }}<br><br>
            {{ form.title }}<br>
            {{ form.media }}<br>
            {{ form.text }}<br>
            <button class="btn btn-success" type ="submit">Создать объявление</button>
        </form>
    </div>
{% endblock %}

test_app/templates/test_app/article_detail.html
{% extends 'flatpages/default.html' %}
{% block content %}
{% block title %}
  <h1>{{ article.title }}</h1>
{% endblock title %}
    <h3><b>статья {{ article_id }}</b></h3>
    <hr>
    <hr>
    {% if article %}
    <table>
        <tr>
            <td><b>файл</b></td>
            <td><b>текст</b></td>
            <td><b>категория</b></td>
            <td><b>действия</b></td>
        </tr>
        <tr>
            {% if article.media %}
            <td><img src="{{ article.media.url }}" width="400" height="400" alt="400"></td>
            {% endif %}
            <td>{{ article.text }}</td>
            <td>{{ article.get_category_display }}</td>
            <td>
                {% if Article.author == request.user.author %}
                <a href="{% url 'article_update' pk=article_id %}"><button><small> Изменить </small></button></a>
                     {% endif %}
                {% if Article.author == request.user.author %}
                <a href="{%  url 'delete' pk=article_id %}"><button><small> Удалить </small></button></a>
                    {% endif %}
            </td>

        </tr>
    </table>
{% else %}
    <h5> Статей пока нет...</h5>
    <h7> Напишите свою </h7>
{% endif %}
  <h2>Оставьте отклик</h2>
  <form action= "{% url 'comment_create' article_id %}" method="post">
    {% csrf_token %}
      {{ form }}
    <button type="submit">Отправить отклик</button>
  </form>
{% if article.comment_set.all %}
    <h5> Все комментарии :</h5>
    {% for comment in article.comment_set.all %}
        <p>Автор комментария: {{ comment.commentUser.username }}</p>
        <h5><a href="{% if comment.pk %}{% url 'comment_edit' pk=comment.pk %}{% endif %}">{{ comment.text }}</a></h5>
    {% endfor %}
{% endif %}
{% endblock content %}

test_app/templates/test_app/article_read.html
{% extends 'flatpages/default.html' %}
{% block content %}
{% block title %}
  <h1>{{ article.title }}</h1>
{% endblock title %}
    <hr>
    <hr>

    {% if article %}
    <table>
        <tr>
            <td><b>файл</b></td>
            <td><b>Текст</b></td>
            <td><b>категория</b></td>

        </tr>
        <tr>
            {% if article.media %}
            <td><img src="{{ article.media.url }}" width="400" height="400" alt="400"></td>
            {% endif %}
            <td>{{ article.text }}</td>
            <td>{{ article.get_category_display }}</td>
        </tr>
    </table>
{% else %}
    <h5> Статей пока нет...</h5>
    <h7> Напишите свою </h7>
{% endif %}
  <h2>Оставьте отклик</h2>
  <form action= "{% url 'comment_create' article.pk %}" method="post">
    {% csrf_token %}
      {{ form }}
    <button type="submit">Отправить отклик</button>
  </form>
{% if article.comment_set.all %}
    <h6> все комментарии :</h6>
    {% for comment in article.comment_set.all %}
    <p> {{ comment.commentUser.username }}</p>
         {% if comment.author == request.user.author %}
             <h5><a href="{% if comment.pk %}{% url 'comment_edit' pk=comment.pk %}{% endif %}">{{ comment.text }}</a></h5>
         {% endif %}
    {% endfor %}
    {% endif %}
{% endblock %}

test_app/templates/test_app/article_update.html
{% extends 'flatpages/default.html' %}
{% block content %}
<head>
    <title>Доработка объявление</title>
</head>
<body>
    <h1>доработка объявления</h1>
    <form action="{% url 'article_update' pk=article.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
         {{ form.category }}<br><br>
            {{ form.title }}<br>
            {{ form.media }}<br>
            {{ form.text }}<br>
        <button type="submit">Внести изменения</button>
    </form>
</body>
{% endblock %}

test_app/templates/test_app/comment_create.html
{% extends 'flatpages/default.html' %}
{% block content %}
<html lang="es-Es">
<head>
    <title>cmment</title>
</head>
<body>

<h1>Ваш комментарий </h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Отправить</button>
</form>
</body>
</html>
{% endblock %}

test_app/templates/test_app/comment_delete.html
{% extends 'flatpages/default.html' %}
{% block content %}
<body>
  <h1>Требуется подтвеждение для удаления комментария</h1>
  <p>Подтвердите,что находясь в твёрдой памяти хотите удалить комментарий</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Подтверждаю</button>
  </form>
</body>
{% endblock %}

test_app/templates/test_app/comment_edit.html
{% extends 'flatpages/default.html' %}
{% block content %}
<head>
    <title>Доработка комментария</title>
</head>
<body>

    <h1>Панель комментария</h1>

         {% if comment.commentUser == request.user %}
                {% csrf_token %}
                <form action="{% url 'comment_edit' pk=comment.pk %}" method="post" enctype="multipart/form-data">
                <a href="{% url 'comment_delete' pk=comment.pk %}"><small> Удалить </small></a>
                {% csrf_token %}
                {{ form.text }}<br>
                <button type="submit">Внести изменения</button>
                </form>
         {% endif %}
         {% if article.author == request.user.author %}
                <a href="{% url 'response' comment.pk %}"><button type="submit">Уведомить</button></a>
         {% endif %}
</body>
{% endblock %}

test_app/templates/test_app/delete.html
{% extends 'flatpages/default.html' %}
{% block content %}
  <h1>Требуется подтвеждение для удаления статьи</h1>
  <p>Подтвердите,что находясь в здравом уме и твёрдой памяти хотите удалить статью</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Подтверждаю</button>
  </form>
{% endblock %}

test_app/templates/test_app/index.html
{% extends 'flatpages/default.html' %}
{% block content %}
    <h1>Список всех Статей :</h1>
<div class="index_articles">
   {% for article in articles %}
       <div class="index_article">
        <h3><a href="{% if article.pk %}{% url 'article_read' pk=article.pk %}{% endif %}">{{ article.title }}</a></h3>
        <p>{{ article.content }}</p>
       </div>
   {% endfor %}
</div>
{% endblock %}

test_app/templates/test_app/profile.html
{% extends 'flatpages/default.html' %}
{% block content %}
 <h1>Страница профиля  {{ request.user.username }}</h1>
  <p>Доброе время суток! Уважаемый {{ request.user.username }}!</p>

  <h2>Список созданных статей :</h2>
<div class="profile_articles">
  {% for article in articles %}
    <div class="profile_article">
      <h3><a href="{% if article.pk %}{% url 'article_detail' pk=article.pk %}{% endif %}">{{ article.title }}</a></h3>
      <p>{{ article.content }}</p>
    </div>
  {% endfor %}
</div>
{% endblock %}

test_app/templates/test_app/response.html
{% extends 'flatpages/default.html' %}
{% block content %}
  <p>Уведомляем пользователя о прочтении коммнетария</p>
  <a href="{% url 'response' comment.pk %}"><button type="submit">Уведомить</button></a>
{% endblock %}

test_app/templates/test_app/user_form.html
<div class="form">

      <ul class="tab-group">
        <li class="tab active"><a href="#signup">Sign Up</a></li>
        <li class="tab"><a href="#login">Log In</a></li>
      </ul>

      <div class="tab-content">
        <div id="signup">
          <h1>Это user_form.html</h1>

          <form action="/" method="post">

          <div class="top-row">
            <div class="field-wrap">
              <label>
                First Name<span class="req">*</span>
              </label>
              <input type="text" required autocomplete="off" />
            </div>

            <div class="field-wrap">
              <label>
                Last Name<span class="req">*</span>
              </label>
              <input type="text"required autocomplete="off"/>
            </div>
          </div>

          <div class="field-wrap">
            <label>
              Email Address<span class="req">*</span>
            </label>
            <input type="email"required autocomplete="off"/>
          </div>

          <div class="field-wrap">
            <label>
              Set A Password<span class="req">*</span>
            </label>
            <input type="password"required autocomplete="off"/>
          </div>

          <button type="submit" class="button button-block"/>Get Started</button>

          </form>

        </div>

        <div id="login">
          <h1>Welcome Back!</h1>

          <form action="/" method="post">

            <div class="field-wrap">
            <label>
              Email Address<span class="req">*</span>
            </label>
            <input type="email"required autocomplete="off"/>
          </div>

          <div class="field-wrap">
            <label>
              Password<span class="req">*</span>
            </label>
            <input type="password"required autocomplete="off"/>
          </div>

          <p class="forgot"><a href="#">Forgot Password?</a></p>

          <button class="button button-block"/>Log In</button>

          </form>

        </div>

      </div><!-- tab-content -->

</div> <!-- /form -->